analysis: which are the biggest officer clusters/cliques and with which percentage are swiss officers a part of them
gabrieltorresgamez/fhnw-san-project pull request #13
Opened 2024-05-17 12:07 UTC by florinbarbisch

2024-05-22 08:20 UTC, buesst1 commented on 99-Swiss officer ratios.ipynb
> +{
<p>nx.projected_graph ;) but ok</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/gabrieltorresgamez/fhnw-san-project/pull/13/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='7'/>

2024-05-22 08:20 UTC, buesst1 commented on 99-Swiss officer ratios.ipynb
> +{
<p>Please add a couple comments to the code.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/gabrieltorresgamez/fhnw-san-project/pull/13/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='10'/>

2024-05-22 08:20 UTC, buesst1 commented on 99-Swiss officer ratios.ipynb
> +{
<p>Title is a bit confusing.</p><p>Number of unique ratios, first five ratios -&gt; textbox in plot (please round numbers)</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/gabrieltorresgamez/fhnw-san-project/pull/13/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='11'/>

2024-05-22 08:20 UTC, buesst1 commented on 99-Swiss officer ratios.ipynb
> +{
<pre class="ql-syntax" spellcheck="false">Line #2.    plot_swiss_officer_ratios_by_group(new_officers_graph, lambda G: k_clique_communities(G, n), f'{n}-clique')
</pre><p>I dont know what this function does but I think its not equivalent to n-cliques in the san script.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/gabrieltorresgamez/fhnw-san-project/pull/13/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='15'/>

2024-05-22 08:36 UTC, buesst1 requested changes
pliiz rename notebook to 02....

See comments above

2024-05-23 14:09 UTC, florinbarbisch commented on 99-Swiss officer ratios.ipynb
> +{
yes, I declared that now

2024-05-23 15:14 UTC, buesst1 approved these changes
LGTM

2024-05-23 15:14 UTC, merged